const CONSTANTS = {
  SETTINGS: {
    UPDATE_DOCUMENT_HEIGHT_TIMEOUT_1: 200, // ms
    UPDATE_DOCUMENT_HEIGHT_TIMEOUT_2: 500, // ms
    DOCUMENT_HEIGHT_MINIMUM_VH: 0.5 // px
  }
}

export default CONSTANTS
